### ISSUE TITLE
Update Opportunity Database Error

### ISSUE THREAD

**Issue by RichHewitt-CODEL** [AndyGilbertCodel/Codel-Portal#1]
**Describe the bug**
When updating an opportunity there is a database error shown in the screenshot below. Also the page is not secure. (http://www.codelportal.com/pages/update_opp_admin.php?pid=449)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'All Opportunities'
2. Search 'Order'
3. Click on 'Edit Opportunity' on opportunity No. 223

**Expected behaviour**
Should be able to edit fields within opportunity.

**Screenshots**
![portal issue 1](https://user-images.githubusercontent.com/45872664/49997204-d5a81e00-ff88-11e8-919f-9c3aa9763b0b.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version ?

**Additional context**

**Comment by AndyGilbertCodel** [comment]
This has now been fixed.
