### ISSUE TITLE
New 'Unsure' Page Found 

### ISSUE THREAD

**Issue by RichHewitt-CODEL** [AndyGilbertCodel/Codel-Portal#10]
![portal issue 4](https://user-images.githubusercontent.com/45872664/50337473-22e83a80-0509-11e9-8548-ad3316edebbc.PNG)

When clicking view/update on a opportunity that has been marked as lost on the 'Cancelled/Lost Opportunities' page.

**Comment by AndyGilbertCodel** [comment]
Fixed
