### ISSUE TITLE
Change 'Order Won' for Distributors & Admins

### ISSUE THREAD

**Issue by RichHewitt-CODEL** [AndyGilbertCodel/Codel-Portal#14]
Currently the distributors are closing orders that are won with unrealistic values, we need to be in control of the value that is contributing to the target if we are going to start using the figures from the portal for reporting without having to go and fudge all the numbers before every board meeting.

Ideally the distributor can still hit the green tick and be asked to put in their order ref. no. as it is now. 

We would then get a message saying 'Distributor X has won an order' with a link to the order where we can enter the accurate final value that will contribute to the target.

**Comment by AndyGilbertCodel** [comment]
Done
