### ISSUE TITLE
CODEL Portal

### ISSUE THREAD

**Issue by DanHodgkinson** [AndyGilbertCodel/Codel-Portal#16]
When going into a distributors dashboard from "users" section on my overview dashboard the yearly totals in the wheel chart don't seem to be updating after a pending order is approved. 

Also when looking at completed orders and clicking to put order in "won date" orders it doesn't seem to put orders dated in 2019 at the top of the list.

**Comment by AndyGilbertCodel** [comment]
Fixed!
