### ISSUE TITLE
Telos Trading Portal Account 

### ISSUE THREAD

**Issue by DanHodgkinson** [AndyGilbertCodel/Codel-Portal#3]
**Describe the bug**
Telos Trading have added a won opportunity on their Portal that is incorrect and needs deleting. 

The line that needs deleting is project E45-Roccaccia worth £36,000. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AndyGilbertCodel** [comment]
Deleted.
