### ISSUE TITLE
Primatec Portal

### ISSUE THREAD

**Issue by DanHodgkinson** [AndyGilbertCodel/Codel-Portal#4]
**Describe the bug**
Need the following updating on the Primatec Portal for won orders so can get the information up to date.

Won order for "Karmøytunellen" @ £5,951 needs deleting as isn't an order on CODEL

Won order for "E16 Gudvanga-og Flenjatunnelen" needs price amending to £18,248 and the order number needs changing to be 106389

Won order "Orders To Date 13/12/18" @ -£28,036 needs deleting as throws everything out value wise.

Thanks

Dan

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AndyGilbertCodel** [comment]
Done.
