### ISSUE TITLE
Distributor Name Corrections

### ISSUE THREAD

**Issue by RichHewitt-CODEL** [AndyGilbertCodel/Codel-Portal#6]
**Describe the bug**
Spelling/Name corrections of distributors as listed below.

HMA - Jon Forman (Capital 'F')
One Gasmaster (No space or capital 'M')
Sinduly SAS (Capital 'S')
Viet An Environment (Changed from Viet-An) - Thuy Le (Changed from Ms Thuy)

**Comment by AndyGilbertCodel** [comment]
Done
